New branch
codehass/Awesome-books pull request #2
Opened 2022-11-30 13:54 UTC by App-Developer8866

Added class for book add and remove from local storage

2022-11-30 14:05 UTC, omarsalem7 reviewed
Hi @codehass , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 💀 

You have submitted a project, that has a non-descriptive pull request title kindly change it and submit it again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-30 17:55 UTC, mikethreels requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 17:55 UTC, mikethreels commented on main.js
> +  bookc.addBook(bookObj);
- [ ] when trying to remove a duplicate book it removes both books instead of 1 of them, you might want to fix this using an Id for each book.

2022-12-01 14:13 UTC, julie-ify requested changes
Hi @App-Developer8866 and @codehass,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 14:13 UTC, julie-ify commented on main.js
>      .join('');
- [ ] You probably won't have this error because you have been working on the app. To replicate this error delete `data` from your local storage and try adding a book. At the first instance of your app, I am unable to add a book, because `data` does not exist in the local storage. I get the error below.

  You can fix this by adding a conditional:
  ```
  if (books != null) {
    showBooks.innerHTML = books
      .map(
        (i) => `
        <div class="element">
        <h5>${i?.title} by ${i?.author} </h5>
        <button onClick='bookc.removeBook(${i?.id})'>Remove</button>
        </div>
        `,
      )
      .join('');
  }
  ```
  ![ido](https://user-images.githubusercontent.com/81468675/205074133-ec17d131-461d-4143-9538-923b8e763e97.jpg)

2022-12-01 14:13 UTC, julie-ify commented on main.js
> +    this.books = JSON.parse(localStorage.getItem('data'));
- [ ] After the issue below you get another one related to this code. You can fix this by resolving `this.books` to an empty array if `data` is null.

  ```
  addBook(obj) {
    this.books = JSON.parse(localStorage.getItem('data')) || [];
    ...
  ```

  ![oeep](https://user-images.githubusercontent.com/81468675/205073830-dfaf2c1e-dc0b-4763-84ab-596bf9bb4956.jpg)

2022-12-01 14:49 UTC, Nemwel-Boniface approved these changes
## Hello team           :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making all the requested changes good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 14:52 UTC, merged